modules
andiemini7/unified-search-platform pull request #19
Opened 2024-06-03 20:12 UTC by festinahuruglica

I created just acf-tools.php and new directory in app acf inside acf.php, the other files (changes from others) when i created the branch comes together

2024-06-04 11:45 UTC, andiemini7 requested changes

2024-06-04 11:45 UTC, andiemini7 commented on acf-tools.php
> +add_action( 'acf/include_fields', function() {
Remove this file

2024-06-04 11:45 UTC, andiemini7 commented on app/acf/acf.php
> +				'param' => 'post_type',
Generate the location automatically for all pages/cpt

2024-06-04 11:45 UTC, andiemini7 commented on app/acf/acf.php
> +	register_post_type( 'modul', array(
Remove this custom post type

2024-06-04 11:45 UTC, andiemini7 commented on template-modules.php
> +    <main id="main" class="site-main" role="main">
Remove this file.

2024-06-04 11:45 UTC, andiemini7 commented on page.php
> +
We need to change this using another method

2024-06-05 06:50 UTC, festinahuruglica commented
Adding the location for custom post types, removing the extra files.

2024-06-06 10:34 UTC, merged