Bone/footer
andiemini7/unified-search-platform pull request #22
Opened 2024-06-04 07:10 UTC by bonefekaa

2024-06-04 11:52 UTC, andiemini7 requested changes

2024-06-04 11:52 UTC, andiemini7 commented on footer.php
> +                      $product_links = array(
Largon custom hardcoded array, use wordpress menu, fetch dynamic data

2024-06-06 11:48 UTC, andiemini7 commented on footer.php
> +$menu_name = 'product_menu';
Why do we need this menu name?

2024-06-06 12:24 UTC, bonefekaa commented on footer.php
> +$menu_name = 'product_menu';
I just set it as a specific footer menu. If you want, you can set the name footer-menu

2024-06-11 08:05 UTC, andiemini7 approved these changes

2024-06-11 08:05 UTC, merged