Responsive navbar
andiemini7/unified-search-platform pull request #26
Opened 2024-06-05 19:15 UTC by alt1nn

2024-06-06 11:56 UTC, andiemini7 requested changes

2024-06-06 11:56 UTC, andiemini7 commented on header.php
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
Remove the cdn, pull from develop and use the tailwindcss that we implemented

2024-06-06 11:56 UTC, andiemini7 commented on index.php
> +            <?php
Remove these paginations

2024-06-06 11:56 UTC, andiemini7 commented on index.php
>      <?php if (have_posts()) : ?>
Remove posts

2024-06-06 11:56 UTC, andiemini7 commented on index.php
>  <div class="container mx-auto p-4">
Move everything with navigation from index.php to header.php

2024-06-06 11:56 UTC, andiemini7 commented on js/main.js
> +jQuery(document).ready(function($){
This needs to be added into assets/js/ create a front.js file and then another navigation.js file, add the navigation changes inside the navigation.js file and import that file inside the front.js. Fix the build from npm run build so it picks up the font.js as the js files and everything imported there

2024-06-06 11:56 UTC, andiemini7 commented on style.css
> +.menu-item-has-children {
Remove all this css, move to assets/scss, create a file named front.scss, then another one navigation.scss move all your css convert it to sass and then import it into font.scss then fix the npm run build pipelines to pickup the front.scss and compile it together with tailwindcss

2024-06-11 08:22 UTC, alt1nn reviewed
files moved

2024-06-25 08:11 UTC, merged